name: Actions testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [ 3.x ]
        architecture: ['x64']

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~\AppData\Local\pip\Cache # This path is specific to Windows
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ matrix.architecture }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ matrix.architecture }}-
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          pip install wheel
          python -m pip install --no-python-version-warning --upgrade pip
          pip install --no-python-version-warning -r requirements.txt
          pip install git+https://github.com/jonisb/jsbc.compat.git#egg=jsbc.compat
          pip install git+https://github.com/jonisb/Toolbox.git#egg=jsbc.Toolbox
          pip install git+https://github.com/jonisb/jsbc.network.git#egg=jsbc.network
          pip install git+https://github.com/jonisb/jsbc.KodiLib.git#egg=jsbc.KodiLib
      - name: Run Kodi
        run: |
          python runkodi.py
      - name: Upload log files
        uses: actions/upload-artifact@v2
        with:
          path: |
            TestInstall\Kodi19_64bit\portable_data\kodi.log
            debug.log
