name: Actions testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.9]
        architecture: ['x64']

    steps:
    - name: curl
      uses: wei/curl@master
      with:
        args: https://mirrors.kodi.tv/releases/windows/win64/kodi-19.0-Matrix-x64.exe
    - run: 7z
