name: Actions testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [ 3.x ]
        architecture: ['x64']

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~\AppData\Local\pip\Cache # This path is specific to Windows
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ matrix.architecture }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ matrix.architecture }}-
            ${{ runner.os }}-pip-
      - name: Cache download
        uses: actions/cache@v2
        with:
          path: public/kodi-19.0-Matrix-x64.exe
          key: ${{ runner.os }}-build-${{ env.cache-name }}-kodi-19.0-Matrix-x64.exe
      - uses: suisei-cn/actions-download-file@v1
        if: hashFiles('public/kodi-19.0-Matrix-x64.exe') == ''
        id: downloadfile  # Remember to give an ID if you need the output filename
        name: Download the file
        with:
          url: "https://mirrors.kodi.tv/releases/windows/win64/kodi-19.0-Matrix-x64.exe"
          target: public/
      - run: dir public
      - run: 7z x public/kodi-19.0-Matrix-x64.exe
      - run: dir
      - name: Run Kodi
        run: |
          python runkodi.py
      - name: Upload log file
        uses: actions/upload-artifact@v2
        with:
          path: |
            portable_data\kodi.log
            debug.log
