name: Test jsbc.KodiLib

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest requests

    - name: Install Xvfb and Kodi
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb software-properties-common
        sudo add-apt-repository -y ppa:team-xbmc/ppa
        sudo apt-get update
        sudo apt-get install -y kodi
        mkdir -p ~/.kodi/userdata
        cat << EOF > ~/.kodi/userdata/guisettings.xml
        <settings version="2">
          <setting id="services.webserver" default="true">true</setting>
          <setting id="services.webserverport" default="true">8080</setting>
          <setting id="services.webskin" default="true">webinterface.default</setting>
          <setting id="services.zeroconf" default="true">true</setting>
          <setting id="services.airplay" default="true">false</setting>
          <setting id="services.airplayvolumecontrol" default="true">true</setting>
          <setting id="services.useairplaypassword" default="true">false</setting>
        </settings>
        EOF
        cat << EOF > ~/.kodi/userdata/advancedsettings.xml
        <advancedsettings>
          <videohardware>
            <usevaapi>false</usevaapi>
            <usevdpau>false</usevdpau>
            <useopengl>true</useopengl>
            <useswrenderer>true</useswrenderer>
          </videohardware>
          <loglevel>1</loglevel>
        </advancedsettings>
        EOF
        chmod 644 ~/.kodi/userdata/*.xml

    - name: Start Xvfb
      run: |
        Xvfb :99 -screen 0 1024x768x24 &
        echo "DISPLAY=:99" >> $GITHUB_ENV

    - name: Start Kodi in background
      run: |
        export DISPLAY=:99
        kodi --standalone &
        timeout 60 bash -c 'until curl -s http://localhost:8080/jsonrpc >/dev/null; do
          echo "Waiting for Kodi to start..."
          ps aux | grep kodi || true
          sleep 5
        done' || { echo "Kodi failed to start within 60 seconds"; cat ~/.kodi/temp/kodi.log; exit 1; }
        echo "Kodi is ready!"

    - name: Run tests
      run: |
        export DISPLAY=:99
        pytest tests/ --verbose

    - name: Debug test failure
      if: failure()
      run: |
        curl -v http://localhost:8080/jsonrpc || true
        cat ~/.kodi/temp/kodi.log || true
        ps aux | grep kodi || true
        pkill kodi || true