name: Test jsbc.KodiLib

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'  # Adjust to your module's Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Or use setup.py if applicable
        pip install pytest  # If using pytest for tests; adjust as needed

    - name: Install Xvfb and Kodi
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb software-properties-common
        sudo add-apt-repository -y ppa:team-xbmc/ppa
        sudo apt-get update
        sudo apt-get install -y kodi

    - name: Start Xvfb
      run: |
        Xvfb :99 -screen 0 1024x768x24 &
        echo "DISPLAY=:99" >> $GITHUB_ENV

    - name: Start Kodi in background
      run: |
        export DISPLAY=:99
        kodi --standalone &  # Runs Kodi in standalone mode
        sleep 30  # Wait for Kodi to fully start (adjust based on logs/timing)

    - name: Run tests
      run: |
        export DISPLAY=:99
        pytest tests/  # Or python -m unittest discover if using unittest

    - name: Stop Kodi (optional cleanup)
      if: always()
      run: |
        pkill kodi || true